### ISSUE TITLE
Many tests broken in ie8

### ISSUE THREAD

**Issue by lukeasrodgers** [es-shims/es5-shim#114]
Using real ie8 (i.e. not ie9's "act as ie8" mode), 57 of the 156 tests are currently failing for me in ie8. Many of these issues are not mentioned under the "dubious shims" section in the README (e.g. tests for filter, indexOf fail). 

Using ie9's emulate ie8 mode, I get 3 failures, all for Object.isExtensible.

**Comment by lukescott** [comment]
I hit this today:

```javascript
var properties = {
    constructor: {}
};
for (var name in properties) {
    console.log(name); // <-- constructor is never iterated even though it is user defined
}
```

Specifically Object.create and Object.defineProperties will not pickup the user defined `constructor` property.

**Comment by ljharb** [comment]
`Object.create` and `Object.defineProperties` aren't in the shim, only the sham - quirks with them are to be expected.

**Comment by ljharb** [comment]
I've added a feature detection to the array tests to determine when it's in an engine that can't distinguish between an absent item, and a present `undefined` - namely, IE 6-8.

This leaves only 3 `Array` tests failing in IE 8 (filed as #341), and all `Array` tests passing in IE 6 and 7.

Any remaining failures in IE 6-8 are real, and either already have issues filed, or, need issues to be filed.
