### ISSUE TITLE
Faster trim

### ISSUE THREAD

**Issue by timo22345** [es-shims/es5-shim#126]
Please consider to replace regexp-based trim with trim27a from here:
http://jsperf.com/mega-trim-test/10

Speed improvement is 10-47x.

trim27 beats all 24 competitors here and beats native trim of Chrome and Chromium and is as fast as Safari's native trim:
http://jsperf.com/mega-trim-test/7

**Comment by lewisje** [comment]
Why does this implementation of String#trim use `aa*` instead of `a+` to match one or more characters?
