### ISSUE TITLE
Class doesn't support automation

### ISSUE THREAD

**Issue by adriangrigore** [es-shims/es5-shim#275]
I'm getting "Class doesn't support automation" error in IE8. Following line (778) seems to be at fault:

    skipConstructor  = ctor && ctor.prototype === object;

That is in the Object.keys shim.

**Comment by ljharb** [comment]
Please reopen if you can provide supporting code that can reproduce the issue.

**Comment by pgn-vole** [comment]
can this issue be re-open ? I'm experiencing the same error in IE8.

You can trigger it with :
```
Object.keys(localStorage) 
```

**Comment by ljharb** [comment]
@pgn-vole localStorage is a host object, not a language builtin, so there's no guarantees with respect to builtin functions.

I'll reopen this, however, to investigate further. If there's a way to detect this case without the perf penalty of a try/catch all the time, I'd love to use it.

**Comment by ljharb** [comment]
Turns out this is `localStorage.prototype.constructor === localStorage` throwing, which is *flabbergasting*. Fix incoming.

**Comment by pgn-vole** [comment]
That was fast! Thanks!

**Comment by ljharb** [comment]
Releasing shortly as `v4.1.8`

**Comment by ljharb** [comment]
Released as `v4.1.8`, and improved in `v4.1.9`.
