### ISSUE TITLE
Array.map broken in ie 8 when working with requirejs and jQuery

### ISSUE THREAD

**Issue by thejourneyoflife** [es-shims/es5-shim#286]
I use requirejs load es5-shim as a deps, find some elements using `$('.xxx').parent('ul')` in a web page,and its broken,debugger later found ,jQuery.map was overwrite by es5-shim's Array.map methods.
How can i fix this error ?

:sos:

**Comment by ljharb** [comment]
That doesn't seem possible. jQuery's `map` function is very different from the one on `Array`.

I also use `es5-shim` and `jquery` consistently on the same page, without any trouble. Perhaps you have a line somewhere that sets `$.fn.map` to `Array.prototype.map`?

**Comment by thejourneyoflife** [comment]
@ljharb Thanks for your reply,But i found nothing about whats you said,I use a third-party lib https://github.com/zTree/zTree_v3/ ,and its broken when my mouse move over it,I debugger and found this trace stack
```
getNodeMainDom:function(target) {
			return ($(target).parent("li").get(0) || $(target).parentsUntil("li").parent().get(0));
},
```
then go to jQuery's sources 
```
 jQuery.fn[ name ] = function( until, selector ) {
                var ret = jQuery.map( this, fn, until );

                if ( !runtil.test( name ) ) {
                        selector = until;
                }

                if ( selector && typeof selector === "string" ) {
                        ret = jQuery.filter( selector, ret );
                }
```
 `jQuery.map` is `es5-shim=>map`  now.

**Comment by ljharb** [comment]
So, that particular lib is using jQuery 1.4.4 which is ancient.

@thejourneyoflife Can you set up a http://jsfiddle.net so that I can reproduce the problem?

http://api.jquery.com/jquery.map/#jQuery-map-object-callback supports objects, so there's no way that `Array.prototype.map` would ever work as a replacement. The `es5-shim` absolutely does not modify *anything* except `Array.prototype` (when it comes to "map") so it can't possibly be to blame.

**Comment by thejourneyoflife** [comment]
@ljharb  jsfiddle.net does't support ie 8,so can not reproduce it,I just comment the es5-shim's `map && filter` methods then it work well

**Comment by ljharb** [comment]
@thejourneyoflife Ah, true. Can you reproduce it with nothing but jQuery, the plugin, and `es5-shim`? In other words, absent your own code? You shouldn't need to comment out those methods.

**Comment by thejourneyoflife** [comment]
@ljharb  Its only happen in a special page and it is too hard too reproduce it,I have't free times this days.

**Comment by ljharb** [comment]
I'm going to close this for now then, I'm pretty confident something in your code is doing `jQuery.map = [].map` or `$.map = Array.prototype.map` or something similar. Please reopen this if you are able to reproduce it on a smaller test case.
