### ISSUE TITLE
Use propertyIsEnumerable in Object.getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by evilpie** [es-shims/es5-shim#289]
Maybe I am missing some context, but shouldn't you be able to use propertyIsEnumerable instead of hardcoding to enumerable: true in getOnwPropertyDescriptor?

**Comment by ljharb** [comment]
If you're referring to https://github.com/es-shims/es5-shim/blob/master/es5-sham.js#L125 - in an environment without true property descriptor support, isn't every property always enumerable?

**Comment by evilpie** [comment]
Yes, right line.
Definitely no, ES3 already had non-enumerable properties (called DontEnum). e.g. all the methods on Object.prototype. ES3 also has propertyIsEnumerable.

**Comment by ljharb** [comment]
I think you're right then - if `propertyIsEnumerable` is available, then we should use it to default the initial "enumerable" value.

PRs welcome :-)
