### ISSUE TITLE
es5-shim causes/exposes bug in Chrome's enumerable properties

### ISSUE THREAD

**Issue by jdelStrother** [es-shims/es5-shim#291]
Hi - I ran into a problem when using Highcharts, which would occasionally generate nonsensical points from valid input data.

I narrowed the problem down to http://jsfiddle.net/ukv6rdj4/1/, copied here for completeness:
```javascript
function optionsToObject (options) {
    var ret = {};
    ret.x = options[0];
    ret.y = options[1];
    return ret;
}

for(var i=0; i<10000; i++) {
    console.log("running...");
    
    var point=optionsToObject([11978120,9871238970]);
    
    // loop over the properties in the point and check that
    // it has a property 'x'
    var foundX=false;
    for(var v in point){
      if (v=='x') foundX = true;
    };
    
    if (!foundX){
      window.grrrr = point;
      throw("'x' doesn't appear in the return value");
    }
}
```

For the first hundred or so calls of `optionsToObject`, the return value looks like `{x:11978120, y:9871238970}`, and enumerating over the properties with `for...in` yields 'x' & 'y'.  After that, I _think_ Chrome's JIT compiler kicks in - at least, I can no longer step into `optionsToObject` in the debugger.  At that point, the return value still looks same, but doesn't yield 'x' when enumerating over properties.

I can only reproduce this when es5-shim is included.  It occurs in Chrome 40.0.2214.94, yet not in Canary (42.0.2294.0).  At this point I'm tempted to just blame Chrome's compiler and assume they've fixed it in 41 or 42, but wondered if anyone here could narrow it down further.

**Comment by ljharb** [comment]
Hmm, this is a strange one.

With the for..in - can you `console.log('v')` and report what properties are found in `point`?

Also, for what it's worth, I'd strongly discourage you from using for..in to enumerate an object's properties (or ever) - `var foundX = Object.keys(point).some(function (v) { return v === 'x'; })` is clearer and will likely not run into these issues. Can you test with that modification?

**Comment by ljharb** [comment]
It's also worth noting that your code in `optionsToObject` will actually avoid optimization - it'd be better as `return { x: options[0], y: options [1] };` so that the shape of the object doesn't change after it's initialized. Probably worth testing with that modification as well?

**Comment by jdelStrother** [comment]
> With the for..in - can you console.log('v') and report what properties are found in point?

It prints `x`,`y`,`x`,`y`,`x`,`y`.... until it just prints `y`.

> Also, for what it's worth, I'd strongly discourage you from using for..in to enumerate an object's properties (or ever) - var foundX = Object.keys(point).some(function (v) { return v === 'x'; }) is clearer and will likely not run into these issues. Can you test with that modification?

Sure - http://jsfiddle.net/ukv6rdj4/3/ .  It shows the same issue, `Object.keys(point)` returns just `["y"]` after a certain point.

> It's also worth noting that your code in optionsToObject will actually avoid optimization - it'd be better as return { x: options[0], y: options [1] }; so that the shape of the object doesn't change after it's initialized. Probably worth testing with that modification as well?

Agreed.   Interestingly, it doesn't produce the error when written that way.  However, this test case is reduced from the original function at https://github.com/highslide-software/highcharts.com/blob/0bd06d9c1a6529f729eeddf6c3b1e54ad5d1c97a/js/parts/Point.js#L68, which doesn't so easily allow the simpler form.

**Comment by ljharb** [comment]
Ah, fair enough. Definitely thanks for providing a reduced test case.

Because refactoring `optionsToObject` in the test case eliminates the problem, I'm absolutely convinced that it's a bug in Chrome's JIT optimization that they've since fixed (things like that seem to break in Chrome every release). It works (up to 100,000 even) in Safari, and breaks for me also in Chrome around 133/135.

I'll leave this open in case anyone can shed some light on it.

**Comment by jdelStrother** [comment]
I filed a bug on v8 - https://code.google.com/p/v8/issues/detail?id=3866&thanks=3866&ts=1423078051 - thought it would be good to get some clarification on exactly what's causing it & whether it's fixed.

**Comment by ljharb** [comment]
Thanks, I agree

**Comment by ljharb** [comment]
This appears to have been fixed in v8 (according to the linked bug). Closing since it's no longer applicable (and wouldn't be fixable in JS-land anyways)
