### ISSUE TITLE
reduce and reduceRight context in strict and non-strict mode

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#298]
I guess this is not such a big concern but while testing `reduce` and `reduceRight` in both `strict` and `non-strict` modes I found something that seems peculiar to me.

On [jsFiddle](http://jsfiddle.net/Xotic750/uw5jcg78/)

```javascript
(function () {
    'use strict';
    
    var arr = [1],
        actual;
    
    arr.reduce(function () {
        actual = this;
    });
    
    console.log('expect "undefined"', actual);
}());

(function () {
    var arr = [1],
        actual;
    
    arr.reduce(function () {
        actual = this;
    });
    
    console.log('expect "global"', actual);
}());
```

And the output

```
expect "undefined" undefined
expect "global" undefined
```

That wasn't what I expected and it is the same on all engines that I have tried.

Of course if the ES5 shims are used then the output is more like I would expect.

```
expect "undefined" undefined
expect "global" Window {top: Window, window: Window, location: Location, external: Object, chrome: Object…}
```

**Comment by ljharb** [comment]
Note how in https://es5.github.io/#x15.4.4.22 step 9.c.ii the spec requires that the "this" value always be `undefined`, whether in strict mode or not - so the shim is actually incorrect here. I'll look into whether it's actually even possible to comply with the spec via a shim here.

**Comment by Xotic750** [comment]
I read the spec before posting and saw 9.c. but I see no mention of "always be undefined"

>Let accumulator be the result of calling the [[Call]] internal method of callbackfn with undefined as the this value and argument list containing accumulator, kValue, k, and O.

Similarly for other methods we see this in the spec, `forEach`

>If thisArg was supplied, let T be thisArg; else let T be undefined.

But in all methods I would expect `strict` and `non-strict` to apply i.e. in `non-strict` mode the values `null` and `undefined` are translated to the global object.

If this really isn't the case for `reduce` and `reduceRight` then they are oddities in the language and as far as I have tested there is no way to shim their behaviour as per spec, meaning that the best you can do is a sham (although nobody will probably ever care with these 2 methods).

**Comment by ljharb** [comment]
Fair point - so because it specifies `[[Call]]`, it follows https://es5.github.io/#x13.2.1 which points to https://es5.github.io/#x10.4.3 - which means you're correct. Thanks for insisting.

So in my Safari JS console, when I do `[1, 2].reduce(function () { 'use strict'; return this === window; });` I get `false`, and `[1, 2].reduce(function () { return this === window; });` I get `true` - I think the issue is that in your fiddle, "reduce" on an array of one item with no initial value specified always just returns the one item straight away. So, on http://jsfiddle.net/uw5jcg78/1/ , it works correctly.

**Comment by Xotic750** [comment]
Haha, yes indeed that would be the problem - the missing initial value meaning that `[[Call]]` is skipped. Thanks. :)
