### ISSUE TITLE
`constructor` in `new Date()` is enumerable

### ISSUE THREAD

**Issue by motapc97** [es-shims/es5-shim#299]
While doing some tests in my own js library, I found out that in Chrome and Firefox, the native `Date` is replaced by es5-shim's Date and the `constructor` property becomes enumerable.

![](http://i.imgur.com/0eWWYSZ.png)

I believe it is because of this code:

````javascript
// Prevent mixups with unfixed Date object
date.constructor = Date;
return date;
````

I know that code is needed to "prevent mixups with unfixed Date object", but is there a way to fix this issue?

I changed the code to this, and it seems to fix my problem:

````javascript
// Prevent mixups with unfixed Date object
if (date.constructor !== Date) {
   date.constructor = Date;
}
return date;
````

Thanks, and sorry for my english

**Comment by ljharb** [comment]
Thanks, you're exactly right!

I'm going to change it to use our internal `defineProperties` which will make sure it's not enumerable.
