### ISSUE TITLE
Object.create(null) incorrectly sets __proto__ in IE 8

### ISSUE THREAD

**Issue by dgreensp** [es-shims/es5-shim#301]
One of the great things about `Object.create(null)` is that `'__proto__' in Object.create(null)` is false.  This is true in modern browsers and IE 9.

You can easily fix this for IE 8 in the sham -- just don't set `__proto__`!

**Comment by ExE-Boss** [comment]
#321 has been merged for 4 years now, I think this should've been closed by now.
