### ISSUE TITLE
Array prototype methods added by es5-shim for example forEach are causing problems when for (var name in someObject) { is used.

### ISSUE THREAD

**Issue by smoothlikejazz** [es-shims/es5-shim#302]
es5-shim is adding bunch of prototype methods to Array object and when for (var name in someObject) { is used with out if( typeof x[name] !== "function" && x.hasOwnProperty(object) ) { it is iterating on methods too. This problem exists only in IE and in other browsers it is not iterating on methods.

IE
```
for (var name in someObject) {
    someObject[name].someProperty // will break in IE as someObject[name] can be forEach method and it will not have someProperty
}
```

We can implement the fix below, but exists in many aspects of our code, which potentially will cause regressions if we don't catch them all

```
if( typeof x[object] !== "function" && x.hasOwnProperty(object) ) {
...
}
```

So my question: Is there anyother way of fixing this?

![ie8_methods_added_to_object](https://cloud.githubusercontent.com/assets/1085669/7503318/047fa230-f3f7-11e4-8e07-d63db8c23c98.png)

**Comment by ljharb** [comment]
What browser are you using? IE 8 and below don't support non-enumerable methods.

Also, `for..in` should never be used on Arrays, ever - and when used, it requires a `hasOwnProperty` check, otherwise you're iterating over the entire prototype. Use a standard for loop, or better, use `forEach` and friends :-)

**Comment by smoothlikejazz** [comment]
I'm unit testing in IE8, thanks for the information and direction @ljharb. I'll be making many changes over the next few days :)
