### ISSUE TITLE
Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by binarykitchen** [es-shims/es5-shim#311]
Despite of including your shim in my project I still see `Unable to get property 'apply' of undefined or null reference` for some older browsers. Isn't es5-shim supposed to wrap `apply()` as well?

**Comment by ljharb** [comment]
I'm not sure that that means. `Function#apply` is part of ES3, and the es5-shim doesn't touch it.

Can you provide a line number, or a browser version, etc?

**Comment by binarykitchen** [comment]
```
Unable to get property 'apply' of undefined or null reference

occured at https://videomail.io/

caused by useragent Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
```

I see plenty errors like these ...

**Comment by ljharb** [comment]
How is this error being recorded?

This doesn't look like an `es5-shim` error, this looks like something in your code is calling `.apply` on something that's `undefined` or `null`.

**Comment by binarykitchen** [comment]
oh, i have some code that traps client-side errors from any visitor and sends this to the server for research.

right, i have to investigate deeper why that element is null ... leave this open for now.

**Comment by ljharb** [comment]
Sounds good. I'd need a specific stack trace (`.stack` on the error object, which you should relay to the server).

But, the specific error message is pretty clear - you're treating `null` or `undefined` as if it's a function, which is a plain and simple JS error, and unrelated to the `es5-shim`.

**Comment by ljharb** [comment]
I'm going to close this pending further information. Happy to reopen it at that time.
