### ISSUE TITLE
IE8 - Win7 - Object doesn't support property or method

### ISSUE THREAD

**Issue by joaom182** [es-shims/es5-shim#313]
IE8 - Win7

Throw the error **Object doesn't support property or method** on the follow line

![2015-06-22_181415](https://cloud.githubusercontent.com/assets/3612098/8293385/7200b1ee-190b-11e5-9f47-09f3b23c8e05.jpg)

**Comment by ljharb** [comment]
Thanks, I forgot ES3 doesn't have `Array#indexOf`. Will fix shortly.

**Comment by ljharb** [comment]
Please do note - this bug isn't in a published version. While I appreciate the bug report and the testing, please only use npm-published or git-tagged versions of `es5-shim`, and not "master".
