### ISSUE TITLE
readme: Badge "http://vb.teelaun.ch/es-shims/es5-shim.svg" broken

### ISSUE THREAD

**Issue by Krinkle** [es-shims/es5-shim#318]
Domain doens't resolve.

**Comment by Krinkle** [comment]
May wanna use https://img.shields.io/ instead:
```
[![npm](https://img.shields.io/npm/v/es5-shim.svg?style=flat)](https://www.npmjs.com/package/es5-shim)
```

[![npm](https://img.shields.io/npm/v/es5-shim.svg?style=flat)](https://www.npmjs.com/package/es5-shim)

**Comment by ljharb** [comment]
This is a recurrence of https://github.com/teelaunch/npm-version-badge/issues/2 - I really prefer the teelaunch badge to this shields badge.

**Comment by ljharb** [comment]
It sounds like the service won't be going back up. Hopefully the owner will send me the code soon, and I'll put the service back up myself.
