### ISSUE TITLE
"Access is denied" error on child iframe in IE8.

### ISSUE THREAD

**Issue by iolo** [es-shims/es5-shim#322]
es5-shim.js Line:855, Char:9

IMHO, `frameElement` should be blacked-listed too.

**Comment by ljharb** [comment]
Can you prepare a jsfiddle the reproduces the issue?

**Comment by ljharb** [comment]
Specifically, is this a child iframe on the same domain?

**Comment by iolo** [comment]
it happens for both same and cross domains.
open https://jsfiddle.net/iolothebard/6jp8ou7t/embedded/result/ in IE8.

**Comment by ljharb** [comment]
Thanks, I'm convinced.

**Comment by iolo** [comment]
thanks ;)

**Comment by ljharb** [comment]
Released shortly as `v4.1.10`
