### ISSUE TITLE
Object.keys and isArguments implementation causes warnings in Immutable.js

### ISSUE THREAD

**Issue by dantman** [es-shims/es5-shim#325]
Immutable.js issues warnings (see facebook/immutable-js#543) when es5-shim is used.

This is because their mixin() uses Object.keys which calls the es5-shim version, which calls isArguments, which then tries to use the `.length` on the prototype, which then triggers Immutable.js' warning that .length is deprecated and `.size()` should be used on Immutable collections.
```js
var isArguments = function isArguments(value) {
    var str = toStr(value);
    var isArgs = str === '[object Arguments]';
    if (!isArgs) {
        isArgs = !isArray(value) &&
          value !== null &&
          typeof value === 'object' &&
          typeof value.length === 'number' &&
          value.length >= 0 &&
          isCallable(value.callee);
    }
    return isArgs;
};
```

As you can see from the isArguments code, after going through the trouble of triggering warnings on any `.length` getter in any library, isArguments ends up returning `false` anyways because the `.callee` isn't callable.

I think a good way to short circuit any `.length` warnings would be to move the `.callee` test up in between the 'object' test and the `.length` is a number test.
```js
var isArguments = function isArguments(value) {
    var str = toStr(value);
    var isArgs = str === '[object Arguments]';
    if (!isArgs) {
        isArgs = !isArray(value) &&
          value !== null &&
          typeof value === 'object' &&
          isCallable(value.callee) &&
          typeof value.length === 'number' &&
          value.length >= 0;
    }
    return isArgs;
};
```

**Comment by ljharb** [comment]
That should be functionally equivalent - my intention was to do the least expensive and most-likely-to-fail checks first.

I assume this is only happening in IE 8?

**Comment by dantman** [comment]
@ljharb No, this happens in all modern browsers. It's not an es5-sham warning. It's a warning that Immutable.js emits when `.length` on an Immutable instance (or in this case the prototype of one) is accessed because use of `.length` has been deprecated on Immutable.js collections.

**Comment by ljharb** [comment]
hm, modern browsers should have a native `Object.keys` - and when not, they should use the `[object Arguments]` code path. I think I have something I can optimize here, which will remove the warning.

**Comment by ljharb** [comment]
Please reopen if this doesn't fix it (should be released in the next day or so). This will still be a problem in IE <= 8 with immutable.js, however.
