### ISSUE TITLE
Date(1441705534578) => Uncaught TypeError: Object.defineProperty called on non-object(…)

### ISSUE THREAD

**Issue by matthewjh** [es-shims/es5-shim#326]
When calling `Date(1441705534578)`, the following is thrown:

````
Uncaught TypeError: Object.defineProperty called on non-object(…)
````

**Comment by ljharb** [comment]
Thanks for the report! In which browser(s)?

**Comment by ljharb** [comment]
nevermind, found it and fixed it. Thanks again!

**Comment by matthewjh** [comment]
Thanks for the quick fix!

From:  Jordan Harband
Reply-To:  es-shims/es5-shim
Date:  Tuesday, 8 September 2015 12:06
To:  es-shims/es5-shim
Cc:  Matthew Hill
Subject:  Re: [es5-shim] Date(1441705534578) => Uncaught TypeError: Object.defineProperty called on non-object(…) (#326)


nevermind, found it and fixed it. Thanks again!
