### ISSUE TITLE
In some cases shim doesn't initializes

### ISSUE THREAD

**Issue by andriy-kudrya-eleks** [es-shims/es5-shim#327]
Under not clear conditions IE doesn't let to access window.localStorage and raises 'SCRIPT5: Access is denied.' error. 
This prevents shim to patch Object/Array.
Actually exception is thrown at window[k] when k === "localStorage"
```javascript
var hasAutomationEqualityBug = (function () {
    /* globals window */
    if (typeof window === 'undefined') { return false; }
    for (var k in window) {
        if (!blacklistedKeys['$' + k] && owns(window, k) && window[k] !== null && typeof window[k] === 'object') {
```

Some discussion about this error is here: https://social.technet.microsoft.com/Forums/en-US/066767a5-f9d5-45f4-95cf-dcd0ff030090/script5-access-is-denied-error-when-accessing-web-sites-using-localstorage?forum=ieitprocurrentver

**Comment by ljharb** [comment]
Lame, simply accessing `window.localStorage` throws an error.

I can wrap this in a further try/catch, I suppose.

**Comment by ljharb** [comment]
@andriy-kudrya-eleks Can you please verify that the latest master fixes your issue?

**Comment by andriy-kudrya-eleks** [comment]
Yeah, thanx
It works )
