### ISSUE TITLE
Invalid Date due to implementation of toUTC method of shim in Safari 8 & 9

### ISSUE THREAD

**Issue by ptacekj** [es-shims/es5-shim#329]
It seem that Safari treats `milliseconds` parameter of `new Date(year, month, day, hours, minutes, seconds, milliseconds)` as an signed integer which causes `toUTC` method to return Invalid Date for otherwise valid timestamps see http://prntscr.com/8svrxd check bellow 
```
new Date(1970, 0, 1,0, 0, 0, 2147483647); // 1970-01-25T19:31:23.647Z
new Date(1970, 0, 1,0, 0, 0, 2147483648); // Invalid Date
new Date(2147483647); // 1970-01-25T19:31:23.647Z
new Date(2147483648); // 1970-01-25T19:31:23.648Z
```

Real life example
```
new Date('2015-07-01T00:00:00'); // Invalid Date in Safari 8 & 9, parseShim calls toUTC(1435708800000)
```

My suggest would be to use `new NativeDate(t)` on https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L1148 unless there is some other compatibility reason not to do so. This solution works at least for this issue.

**Comment by ljharb** [comment]
Wow, good catch, thanks!

I'll see what's the most reliable approach here and do some browser testing.

**Comment by ljharb** [comment]
It seems like your suggestion won't work, sadly, because `new Date('2015-07-01T00:00:00')` is supposed to be parsed in local time - that change makes it parse in UTC.

**Comment by ljharb** [comment]
@ptacekj Please file this on http://bugs.webkit.org as well! They can at least fix it for the next Safari :-)

**Comment by ljharb** [comment]
I've got tests and a fix for this; I'll merge it after verifying that it's still working in all browsers.

**Comment by ljharb** [comment]
@ptacekj Thanks! I think this should fix it in all browsers. I'll release it shortly.

**Comment by ptacekj** [comment]
Thank you!

**Comment by ljharb** [comment]
Thank *you*! This is super obscure and in a modern browser. I'm going to file an issue with Webkit (feel free to beat me to it and post it here) and when I'm finished with my current webkit patch, I'll fix it if it's not addressed yet.

**Comment by ljharb** [comment]
Filed as https://bugs.webkit.org/show_bug.cgi?id=150386
