### ISSUE TITLE
String.prototype.lastIndexOf broken in IE11

### ISSUE THREAD

**Issue by polygonplanet** [es-shims/es5-shim#331]
String.prototype.lastIndexOf is broken when Unicode character and second argument specified.

```javascript
'abcあい'.lastIndexOf('あい', 1);
```

expected: -1
IE11: 3

**Comment by ljharb** [comment]
Good catch!

According to http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.lastindexof - the `position` argument is actually used for the *end* of the string to look *left* from - ie, it is indeed spec-compliant behavior for `'abcあい'.lastIndexOf('あい', n);` to return `-1` when `n` is less than `'abcあい'.indexOf('あい');`.

This also appears to be broken in Edge, and IE 9 and 10 - although in IE 8 it works perfectly!
