### ISSUE TITLE
Consistency of `parseInt` shim.

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#332]
As mentioned in https://github.com/paulmillr/es6-shim/pull/369#issuecomment-153654751

There seems to be inconsistency between native `parseint` and the shim with respect to the treatment of string number literals that are hexadecimal and that are preceded with `+/-`. All working native versions appear to accept `'-0x1'` and parse it as `-1`, but with the shim I do not believe this is the case.
```
// ES-5 15.1.2.2
if (parseInt(ws + '08') !== 8 || parseInt(ws + '0x16') !== 22) {
    /* global parseInt: true */
    parseInt = (function (origParseInt) {
        var hexRegex = /^0[xX]/;
        return function parseInt(str, radix) {
            var string = $String(str).trim();
            var defaultedRadix = $Number(radix) || (hexRegex.test(string) ? 16 : 10);
            return origParseInt(string, defaultedRadix);
        };
    }(parseInt));
}
```

**Comment by ljharb** [comment]
Per http://www.ecma-international.org/ecma-262/6.0/#sec-parseint-string-radix, you are correct. I'll fix the implementation.
