### ISSUE TITLE
IE < 8 Array~join inconsistency with `undefined`

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#333]
Tests
```
affirm.strictEqual([1, 2].join(), '1,2', 'defaults to comma');
affirm.strictEqual([1, 2].join(undefined), '1,2', 'defaults to comma');
```
Patch
```
var pJoin = Array.prototype.join;
Array.prototype.join = function (separator) {
  if (typeof separator === 'undefined') {
    separator = ',';
  }
  return pJoin.call(this, separator);
};
```
http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.5

**Comment by ljharb** [comment]
This is impossible to fix, because IE 6-8's JS engine has a bug in that it can not differentiate sparse arrays from arrays with `undefined`.

**Comment by Xotic750** [comment]
This fix is specifically for `seperator` is `undefined` and does not tackle IE6-8 spareness issues.

**Comment by ljharb** [comment]
aha, thanks for clarifying
