### ISSUE TITLE
String in some older environments doesn't handle null and undefined correctly.

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#335]
Sorry, can't remember the actual environments, but tests
```
var actual;
affirm.doesNotThrow(function () {
  actual = String();
});
affirm.strictEqual(actual, '');
affirm.doesNotThrow(function () {
  actual = String(undefined);
});
affirm.strictEqual(actual, 'undefined');
affirm.doesNotThrow(function () {
  actual = String(null);
});
affirm.strictEqual(actual, 'null');
```
and patch (though may not be so simple, like your experience with Number in es6.shim)
```
var nativeString = String;
String = function(value) {
  if (!arguments.length) {
    return '';
  }
  if (typeof value === 'undefined') {
    return 'undefined';
  }
  if (value === null) {
    return 'null';
  }
  return nativeString(value);
};
```
http://www.ecma-international.org/ecma-262/5.1/#sec-15.5.2.1

**Comment by ljharb** [comment]
Thanks - I would need to know in which environment `String(null) !== 'null'` before trying to fix this one, not the least because it's pretty invasive, since `String` is called a lot. In addition, I assume this wouldn't fix `null + '' === 'null'`?

**Comment by Xotic750** [comment]
I don't have any info on `null + ''` and since the close down of testling I am unable to go back and check things out (I wrote loads of tests to find problems), that's partly why I'm sharing stuff that I had found rather than trying to maintain what I have. What I can say is that lodash has implemented `toString` and the decision there was for `value == null` to return `''`. I understand if you don't take it further, I guess you also suffered the the same closure.

**Comment by ljharb** [comment]
Testling only went down to IE 6, Opera 10, etc - I have browserstack so I can manually verify in those environments. IE 6+, Opera 10.6+, Chrome 14+, FF 3+, Safari 4+, all are correct in this.

I'm going to close this issue until we can figure out an environment that doesn't handle this correctly. I'm also highly skeptical that this is actually a real problem, since it would have broken almost all JS on the internet.

**Comment by Xotic750** [comment]
No problem, if I come across the information I will post it here. It may have even been from something older, even NetScape or something.

**Comment by Xotic750** [comment]
Looking back through my info, it was not `String` that was broken/buggy but `Object.prototype.toString`. Some environments did not return `[object Undefined]` and `[object Null]`, plus some returned the incorrect `[[Class]]` for some objects. I have the tests, which I can post in a new ticket. The `null` and `undefined` are easy fixes and would work cross frame. Some of the others are easy enough to fix locally, but far more complex if you want them cross frame. Are you interested in the tests or even fixing `Object`'s `toString`?

**Comment by ljharb** [comment]
Please file an issue for each violation you're aware of. In some cases it may not be worth it to do, but I'd love the issue documenting it regardless. However, for this specific one, #304 talks about how it's not possible to fix.

**Comment by Xotic750** [comment]
Aha, didn't realise there was a ticket open for it. I will have a look but I could swear that I had a fix for it, think it used `evil`. I will have a dig and see what I have.

**Comment by Xotic750** [comment]
Nope, I ended up creating an abstract function called `toStringTag`.
