### ISSUE TITLE
IE < 8 `toPrecision` throws when passed `undefined`

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#340]
Test
```
assert.doesNotThrow(function () {
  (1.2345).toPrecision(undefined);
});
```
Fix
```
var nativeToPrecision = Number.prototype.toPrecision;
Number.prototype.toPrecision = function (precision) {
  var x = Number(this);
  if (!arguments.length || typeof precision === 'undefined') {
    return String(x);
  }
  return nativeToPrecision.call(x, precision);
};
```
http://www.ecma-international.org/ecma-262/5.1/#sec-15.7.4.7

ES6 has a slightly difference spec and uses the abstract `thisNumberValue` instead of `Number`.
http://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.toprecision
http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-number-prototype-object
So, would need to be patched again in es6-shim.

**Comment by ljharb** [comment]
Thanks!

**Comment by Xotic750** [comment]
You're welcome, just going through my bits and pieces and looking for stuff that es5.shim doesn't have yet. ;)
