### ISSUE TITLE
string.split() misbehaving in 4.3.0

### ISSUE THREAD

**Issue by garron** [es-shims/es5-shim#342]
We're using es5-shim as part of running our tests in phantomjs 1.9.15.

Using es5-shim 4.2.0:
> console.log('abc'.split(/([b])/));
[ 'a', 'b', 'c' ]

Using es5-shim 4.3.0:
> console.log('abc'.split(/([b])/));
[ 'a', [ 'b' ], 'c' ]

**Comment by ljharb** [comment]
Thanks for the report! I'll investigate and see if I can write a reproducible failing test.

**Comment by ljharb** [comment]
Looks like this broke in dcce96ae21185a69d2d40e67416e7496b73e8e47 - thanks, I've found the bug!

**Comment by ljharb** [comment]
Released as [`v4.3.1`](https://github.com/es-shims/es5-shim/releases/tag/v4.3.1)
