### ISSUE TITLE
Module parse failed when using babel

### ISSUE THREAD

**Issue by sherlock917** [es-shims/es5-shim#343]
when i use babel to compile my scripts with es5-shim imported, the compiler throws an error: 

> ERROR in ./~/es5-shim/es5-shim.js
> Module parse failed: /***/node_modules/es5-shim/es5-shim.js Line 1482: Unexpected token .
> You may need an appropriate loader to handle this file type.
> |     var hasToPrecisionUndefinedBug = (function () {
> |         try {
> |             return 1.0..toPrecision(undefined) === '1';
> |         } catch (e) {
> |             return true;
> @ ./src/p/index/index.js 3:0-19

**Comment by ljharb** [comment]
The source code is `1.0.toPrecision` - I'm not sure where the extra dot is coming from. Are you using the latest `es5-shim`? Perhaps it's a babel bug - although babel doesn't usually transpile into node_modules. Why is it loading from `~/es5-shim` instead of from a `node_modules` folder?

**Comment by sherlock917** [comment]
I tried moving es5-shim.js into my project and importing it with a relative path, still got that error. Seems the only way to get rid of it is changing `1.0.toPrecision` to `(1).toPrecision`, and it compiled to `1..toPrecision`, exactly the same as the corresponding line in es5-shim.min.js. Not sure why, `1.0.toPrecision` actually works fine in every console. Probably a babel problem.

**Comment by ljharb** [comment]
Please file it on babel's side! I can change it here if they won't fix it soon.

**Comment by ljharb** [comment]
In abbel, `1.0.toPrecision(3)` transpiles to `1.0..toPrecision(3)`, `(1.0).toPrecision(3);` → `1.0..toPrecision(3);`, however `1.1.toPrecision(3);` → `1.1.toPrecision(3);`. definitely a babel bug.

**Comment by sherlock917** [comment]
Issue filed, thx for the explanation.
