### ISSUE TITLE
Enhancement: Have `JSCS` options set for actual coding style.

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#356]
[`JSCS`](http://jscs.info/) can auto fix a number of issues (and format), but if I run `fix` on the code then it generates a lot of line spaces, and even creates conflicts with the options that you have set for `eslint`. It would be nice if the packages had matching options, the code was run though fix, so when modifying/adding code to the project other could run `fix` to make sure the changes match the rest of the style. Adding a `.jscsrc` to other code director would also be nice, i.e. tests. 

This is not something that I feel that I can do, it's not my project and not my style choices.

Just some thoughts.

**Comment by ljharb** [comment]
`eslint` has a fix mode too, fwiw. This repo already passes `jscs` because it has a `.jscs.json` - so there shouldn't be anything *to* fix.

**Comment by Xotic750** [comment]
Aha, I didn't know about `eslint`, I will try that instead. It was just that I ran `jscs` fix and the whole layout changed and `eslint` also complained about the formatting.

**Comment by Xotic750** [comment]
`eslint` fix does not work for me, seems there is something missing?
```
[graham@tyr es5-shim]$ eslint --fix es5-shim.js 
/home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:213
                    throw e;
                    ^

Error: Cannot find module '@ljharb/eslint-config'
Referenced from: /home/graham/source_projects/es5-shim/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfigFromFile (/home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:176:22)
    at /home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:191:36)
    at getLocalConfig (/home/graham/node-v4.1.0-linux-x64/lib/node_modules/eslint/lib/config.js:321:23)
```

**Comment by ljharb** [comment]
You're misusing both eslint and jscs - you can't use globally installed copies, you have to use the local ones in `node_modules/.bin`, so they are both the correct versions and use the correct config files.

**Comment by Xotic750** [comment]
`eslint` is globally installed. I will remove it and try agin. `jscs` is not globally installed, only locally. I'm not sure how I am misusing them otherwise? When executing either from the root of the project, they both look at the project's config files.

**Comment by ljharb** [comment]
For `eslint`, it depends on having the shared config it extends installed, which is installed locally. As for `jscs`, I'm not sure, I don't use the autofix option on any linters.

**Comment by Xotic750** [comment]
Removing the globally installed copy of `eslint` fixed the above issue. But running `fix` removes the leading `;`, I guess it is a pattern that is unknown and expects `;(function () {}())`
```
 // Add semicolon to prevent IIFE from being passed as argument to concatenated code.
-;
+
```
The `jscs` fix is really useful, because you easily copy and paste between projects and it normally does all the whitespace formatting for me so that I don't have to worry about fixing 2, 4, or 8 leading whitspaces, and thngs like required line breaks (or no line break) and stuff. But it's just not working for me on `es5.shim`. I'll take a little closer look at it to see if I can find a reason why, it's always possible that I have something configured incorrectly for only this project.

**Comment by Xotic750** [comment]
Ok, for some reason `jscs` is now working as expected, the only change that I made was removing `eslint` globally. Weird. :/
