### ISSUE TITLE
JScript memory management

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#362]
I was reading through some old articles,  and this one by @jdalton
[Incorrect ES5 fallbacks](https://gist.github.com/jdalton/1120592#es5-shim-v124 )
Where he says
>I'm a little harder on es5-shim because its goal is to follow the specification as closely as possible. Besides the listed implementation issues I noticed heavy use of named function expressions which will leak a super-tiny bit of memory in IE (this aggravates my dev OCD more than any real world memory consumption concerns).

Which relates to
[JScript memory management](http://kangax.github.io/nfe/#jscript-memory-management)

Looking through the code, I see examples of this pattern. This may or may not be of concern to you but I thought I'd mention it.

**Comment by ljharb** [comment]
I have a strong preference for NFEs over function declarations, and the memory difference discussed in that 4 year old gist is so tiny as to be negligible.

Thanks for bringing it up!

**Comment by Xotic750** [comment]
I thought you would be aware of it, just thought I'd post it while it was in front of me. :;
