### ISSUE TITLE
Date.prototype.toISOString called on non-finite value with Adobe Scripting

### ISSUE THREAD

**Issue by ianbytchek** [es-shims/es5-shim#365]
Trying to make use of es5-shim with Adobe Scripting, but getting the following exception:

![image](https://cloud.githubusercontent.com/assets/1086845/11708744/a8fe885e-9f22-11e5-920e-15358165e400.png)

Trying to do a very basic thing with:

```js
require('es5-shim');

$.writeln(Object.keys({
    "foo": 1,
    "bar": 2
}));
```

**Comment by ljharb** [comment]
Do you know if it's the `require` that causes it, the `$.writeln` call, or the `Object.keys` call?

**Comment by ianbytchek** [comment]
It's `Object.keys`. Everything else works fine on it's own. I'm able to do `Object.keys` with MDN's polyfill, but adding polyfills for everything is reinventing the wheel.

![image](https://cloud.githubusercontent.com/assets/1086845/11708859/7ca13954-9f23-11e5-867f-a97d2c281b93.png)

**Comment by ianbytchek** [comment]
Well. Actually sorry. The error gets cause from the require part, if I understand correctly it never gets to `Object.keys`.

**Comment by ljharb** [comment]
Can you confirm whether or not `try/catch` works in Adobe scripting? the es5-shim throws errors frequently to detect runtime bugs, but it wraps them all in a try/catch. I'm wondering if Adobe ignores that.

**Comment by ianbytchek** [comment]
Yep.

```js
try {
    require('es5-shim');
} catch (error) {
    $.writeln('Caught an error:', error);
}

// Caught an error:Error: Date.prototype.toISOString called on non-finite value.

$.writeln(Object.keys({
    "foo": 1,
    "bar": 2
}));

// foo,bar
```

`Object.keys` also works!

**Comment by ljharb** [comment]
OK, that's great! It means it's fixable. Does `error.stack` contain anything? That would be most helpful (ie, not just the line that throws, but the stack trace that led there)

**Comment by ianbytchek** [comment]
`stack` is `undefined`. those are the properties of the error: number, fileName, line, source, start, end, message, name, this.

**Comment by ljharb** [comment]
Sorry for the back and forth - if any of that info points to anything besides that toISOString error, that would be very helpful.

**Comment by ianbytchek** [comment]
Happy to help, don't worry. Nope, my understanding is that it goes from top to bottom – it hits the first issue and throws an error, meaning there might be something further down the line. I just tried disabling the `defineProperties` execution, no other errors were thrown, fingers crossed this is the only one.

**Comment by ljharb** [comment]
ok a few more questions - what does `new Date(-1).getTime()` and `new Date(-62198755200000).getTime()` return?

**Comment by ianbytchek** [comment]
```js
$.writeln(new Date(-1).getTime());
// -1

$.writeln(new Date(-62198755200000).getTime());
// -62198755200000
```

**Comment by ianbytchek** [comment]
@ljharb I noticed you pushed a bunch of commits recently. Any chance they resolve this case? I'd offer a pr, but assume that this is something tricky?

**Comment by ljharb** [comment]
No, I haven't resolved this yet. Since I can't repro it myself, and since I don't know exactly what's failing, I'm a bit lost.

Can you confirm that if you comment out the `hasNegativeDateBug` and `hasSafari51DateBug` checks (replacing them with a literal `false`, for example), that the shim loads successfully? Even if I don't know why the lines are failing, knowing which ones are throwing would help.

**Comment by ianbytchek** [comment]
Yep, setting those two to `false` eliminates the error, that's what I meant in https://github.com/es-shims/es5-shim/issues/365#issuecomment-163537556. `isFinite` is causing a problem with `Date` that was constructed with a string with a negative number. See this:

```
$.writeln(isFinite(new Date(-1)));
// true
$.writeln(isFinite(new Date('-1')));
// false
$.writeln(isFinite(new Date(-62198755200000)));
// true
$.writeln(isFinite(new Date('-62198755200000')));
// false
$.writeln(isFinite(new Date(1)));
// true
$.writeln(isFinite(new Date('1')));
// true
```

…some time later: Oh dear, I tried finding workaround and discovered that the first time shim is applied – it works, but goes wrong when it's being run the second time… That is because Adobe keeps the JS environment for the entire app session, so here's what happens:

1. Script checks those two things, doesn't find `toISOString` and successfully adds it.

    ```js
	var hasNegativeDateBug = Date.prototype.toISOString && new Date(negativeDate).toISOString().indexOf(negativeYearString) === -1;
	var hasSafari51DateBug = Date.prototype.toISOString && new Date(-1).toISOString() !== '1969-12-31T23:59:59.999Z';
    ```

2. The second time it runs it finds `toISOString` and executes it. Apparently there is also no `getUTC…` methods, because they are failing next, though they are [specified](http://jongware.mit.edu/iljscs6html/iljscs6/pc_Date.html) in the older docs. But the latest version differs from CS6 – nothing surprising it's gone.

Updating the following block works and shouldn't affect other environments. 

```js
…
var hasUTCMethods = Date.prototype.getUTCFullYear && Date.prototype.getUTCMonth && Date.prototype.getUTCDate && Date.prototype.getUTCHours && Date.prototype.getUTCMinutes && Date.prototype.getUTCSeconds && Date.prototype.getUTCMilliseconds;
var hasNegativeDateBug = Date.prototype.toISOString && new Date(negativeDate).toISOString().indexOf(negativeYearString) === -1;
var hasSafari51DateBug = Date.prototype.toISOString && new Date(-1).toISOString() !== '1969-12-31T23:59:59.999Z';
    
hasUTCMethods && defineProperties(Date.prototype, {
…
```

**Comment by ljharb** [comment]
OK, so - you're saying that CS doesn't have any of `Date#{getUTCFullYear, getUTCMonth, getUTCDate, getUTCHours, getUTCMinutes, getUTCSeconds, getUTCMilliseconds}`?

If not, I'll want to shim all of those as well.

**Comment by ljharb** [comment]
@ianbytchek if you could try checking on latest master, I suspect we'll now see an error on the *first* sourcing of the file, because those UTC methods aren't a function.

**Comment by ianbytchek** [comment]
> OK, so - you're saying that CS doesn't have any of `Date#{getUTCFullYear, getUTCMonth, getUTCDate, getUTCHours, getUTCMinutes, getUTCSeconds, getUTCMilliseconds}`?

That's right @ljharb. Just checked the master, can't see any difference in behaviour, it doesn't fail the first time and fails on consecutive runs like before on this line:

```js
throw new RangeError('Date.prototype.toISOString called on non-finite value.');
```

Might have you missed the point about the constant js environment? The main problem is that shim sees different things when it checks at what needs to be done when it runs for the first time and when it runs consecutively in the same environment.

**Comment by ljharb** [comment]
@ianbytchek yes, I got that :-) the issue seems to be that the `toISOString` shim depends on the presence of those UTC methods. however, the `RangeError` suggests it might be something else. Could you try editing that line - 1278 in my copy - to somehow print out or console.log the `this` value? I'm curious what it is that's not finite.

**Comment by ianbytchek** [comment]
@ljharb just making sure :blush: See below.

```js
$.writeln(this);
// Fri Jan 01 -1 04:00:00 GMT+0400
$.writeln(typeof this);
// object
```

**Comment by ljharb** [comment]
Thanks - what about `+this` and `Number(this)` and `this.getTime()`?

**Comment by ljharb** [comment]
@ianbytchek any update? sorry for all the back and forth, but without a copy of Photoshop for my to test myself, it's hard for me to verify that a fix will work.

**Comment by ianbytchek** [comment]
@ljharb sorry, this got out of hands. I'll look into this towards the end of the week and will report. Happy to help.

**Comment by ljharb** [comment]
Thanks, much obliged!

**Comment by ianbytchek** [comment]
@ljharb here's what I've got. What do you think?

```js
if (!isFinite(this)) {
    $.writeln(this); // Fri Jan 01 -1 04:00:00 GMT+0400
    $.writeln(typeof this); // object
    $.writeln(+this); // NaN
    $.writeln(Number(this)); // NaN
    $.writeln(this.getTime()); // -62198755200000

    throw new RangeError('Date.prototype.toISOString called on non-finite value.');
}
```

**Comment by ljharb** [comment]
@ianbytchek Thanks! From here I think I can figure out what might be the issue - if you want to try making the condition `if (!isFinite(this) && !isFinite(this.getTime()) {` and see if that fixes your problem, that's my hunch.

It's super bizarre that a Date object would have a finite `getTime()` but coerce to a number that's different than that. Presumably `var date = new Date(-62198755200000); [+date, Number(date), date.getTime()]` also produces `[NaN, NaN, -62198755200000]`?

**Comment by ianbytchek** [comment]
@ljharb replacing condition with `if (!isFinite(this) && !isFinite(this.getTime()) {` worked! Also, yes, doing that produces the expected outcome. Please update master.

```js
if (!isFinite(this)) {
    var date = new Date(-62198755200000);
    $.writeln(+date); \\ NaN
    $.writeln(Number(date)); \\ NaN
    $.writeln(date.getTime()); \\ -62198755200000

    throw new RangeError('Date.prototype.toISOString called on non-finite value.');
}
```

**Comment by ljharb** [comment]
Released as v4.5.5

**Comment by ianbytchek** [comment]
@ljharb :+1: :beers:

**Comment by ljharb** [comment]
Thanks for reporting this and following through back and forth :-) I love these kinds of quirky environment issues.

**Comment by ianbytchek** [comment]
Try do something with adobe scripting, bet you'll change your mind! :smile: But there is that strange satisfaction… like when taking an old car, stuffing it with latest technology and see it rolling.

**Comment by matsilva** [comment]
Thanks guys, this just helped me!
