### ISSUE TITLE
es5-sham cause IE8 run slowly

### ISSUE THREAD

**Issue by BorelTung** [es-shims/es5-shim#369]
Developing web application with webpack, I want it to support IE8.
Since es5-shim does not support object.freeze, I use es5-sham. But it does not work and even cause IE8 to show this alert:
Script on this page is causing internet explorer to run slowly.

**Comment by ljharb** [comment]
`Object.freeze` makes every browser run slowly, fwiw.

Can you provide a jsfiddle that reproduces this? It's likely the combination of scripts, not es5-sham itself, that's causing that.

**Comment by ljharb** [comment]
I'm going to close this pending a reproducible test case.
