### ISSUE TITLE
[IE8] es5-shim: hasStringJoinedBug fails

### ISSUE THREAD

**Issue by tonekk** [es-shims/es5-shim#370]
https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L834

This line breaks in IE8 and IE10.
Currently I don't have a windows computer to give you the original message, but it is something like:
`this is not a javascript object`

**Comment by ljharb** [comment]
It works just fine for me in both IE 8 and IE 10. Do you have any other libraries loaded before `es5-shim` that might be changing the global environment?

**Comment by tonekk** [comment]
Currently setting up my VM. Will provide followup info

**Comment by esiqveland** [comment]
I am seeing this issue with:
```Array.prototype.join: this is not a javascript object``` on this line with IE7-9 in compat mode in IE11.

**Comment by ljharb** [comment]
hmm, i typically only test browsers in standards mode - it works fine in proper IE 7, 8, 9, 10, and 11, but I haven't checked in compat mode. I'll take a look.

**Comment by ljharb** [comment]
ok, well, compat mode instantly reproduced it in IE 11. nobody should be using compat mode :-) but, people do, so I'll fix this ASAP.

**Comment by tonekk** [comment]
Thank you ;)
We are using it with the C# Webview. I'm not sure if that is compat mode, but it breaks also

**Comment by ljharb** [comment]
Released as `v4.4.1`. Thanks all for your reports!

**Comment by tonekk** [comment]
:+1: Already using new release ;)
