### ISSUE TITLE
IE8 403.14 IIS Express issue with es5-shim

### ISSUE THREAD

**Issue by mcpDESIGNS** [es-shims/es5-shim#372]
I'm not sure why this is coming up (it didn't use to), but all of a sudden my project using IISExpress is throwing a 404.13 because it is now looking for `es5-shim.map` ??

It's causing a 404 here:    /Public/JS/Vendor/es5-shim.map

I have only the `es5-shim.min.js` file in that directory, what could of made it now start **looking** for this .map file, there's no reference to it anywhere in the project besides in the file (es5-shim) itself.

**Comment by Xotic750** [comment]
In the minified file there is a reference
`//# sourceMappingURL=es5-shim.map`

Have you upgraded `IISExpress`, it sound like it now recognises this comment and looks for the file?

**Comment by mcpDESIGNS** [comment]
I don't believe I have but that could possibly be it. I added the file, and it still gives the error.

It actually gives this as well now for the `map` file:

`Expected ';'`
`es5-shim.map, line 1 character 11`

Which is here, what in the world is it talking about ! hah

    {"version" : // <-- basically the first thing in the file hah

**Comment by Xotic750** [comment]
You could try deleting the line `//# sourceMappingURL=es5-shim.map`, it will not affect `es5-shim` functionality, but I suspect that something has changed on your end as that line has been there for a long long while.

**Comment by mcpDESIGNS** [comment]
Just tried removing that line and it's still causing a 403.14 Unauthorized I'll keep looking..

**Comment by ljharb** [comment]
First, a 404 isn't something one should be concerned about. Second, that 404 is happening because a browser is reading the source map comment via the dev tools and attempting to load the source map. Is there a reason you're not including the source map in production?

**Comment by mcpDESIGNS** [comment]
I believe it is something very strange going on with the project, it seems to be some what linked to html  mode in angular as well. I'll close this one,just thought maybe someone ran into this as well! I'll post whatever crazy solution I find incase it happens to anyone else!

**Comment by mcpDESIGNS** [comment]
Thank you for your quick help @Xotic750, really appreciate it!
