### ISSUE TITLE
Array.from(arrayLike[, mapFn[, thisArg]])

### ISSUE THREAD

**Issue by cuixiping** [es-shims/es5-shim#375]
The [Array.from()][1] method creates a new Array instance from an array-like or iterable object.

`Array.from(arrayLike[, mapFn[, thisArg]])`

Should this method be added?

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by zloirock** [comment]
Should not. It was added in ES6. You can use [`core-js`](https://github.com/zloirock/core-js) or [`es6-shim`](https://github.com/paulmillr/es6-shim).

**Comment by ljharb** [comment]
Indeed - es5-shim is only for ES5.
