### ISSUE TITLE
does not work with `slice` on IE8

### ISSUE THREAD

**Issue by BorelTung** [es-shims/es5-shim#376]
showing: Object doesn't support property or method 'slice'

**Comment by Xotic750** [comment]
Then it is likely that whatever you are calling the method `slice` on is not an Array, e.g.
```
var yourObject = {};
console.log(yourObject.slice());
```

**Comment by ljharb** [comment]
@BorelTung can you be more specific? Only Arrays and strings have `slice`, but both definitely work in IE 8. A code sample that can reproduce this problem would be helpful.

**Comment by BorelTung** [comment]
You are right. It seems a bug of webpack, which builds codes calling `slice` on [object object].
