### ISSUE TITLE
properlyBoxesContext throws when loaded after prototypejs 1.7.0.0 and older

### ISSUE THREAD

**Issue by gkatsev** [es-shims/es5-shim#377]
See https://jsfiddle.net/gkatsev/oesj5krb/2/ for a live example.
The runtime check ends up invoking prototypejs code and in version 1.7.0.0 and older of the library this ends up throwing an error because a method that prototypejs expects doesn't exist.
version 1.7.1.0 of prototypejs doesn't have this issue because it ends up wrapping the native methods properly in some cases.
es5-shim probably should not throw an error when in such a setting.

**Comment by Xotic750** [comment]
I'm curious as to why you would load prototypejs before es5-shim, rather than vice-versa?

**Comment by ljharb** [comment]
That was my question, but sadly it's on a customer's page that they don't control.

**Comment by Xotic750** [comment]
Perhaps the documents should clearly state that es5-shim (es5-sham, es6-shim and es7.shim etc) are expected to be loaded first and in a particular order as they are patching the JavaScript engine, even though it seems like common sense.

**Comment by ljharb** [comment]
@Xotic750 a PR to add that verbage would be just fine. Regardless, this should be fixed.

**Comment by gkatsev** [comment]
The issue at hand isn't what the correct usage of es5-shim is. It's whether es5-shim should throw an error when used in this way. It probably should not.

**Comment by ljharb** [comment]
Published as [v4.5.1](https://github.com/es-shims/es5-shim/releases/tag/v4.5.1)

**Comment by gkatsev** [comment]
@ljharb thanks.
