### ISSUE TITLE
`new Date()` broken in IE8

### ISSUE THREAD

**Issue by riophae** [es-shims/es5-shim#389]
```js
var date = new Date(new Date());
// expected to be a valid `Date` Object, got `new Date(NaN)` in IE8 instead
```

IE8 (with `es5-shim`):
<img width="486" alt="2016-02-24 16 30 51" src="https://cloud.githubusercontent.com/assets/1289884/13279649/4ad2714a-db14-11e5-97e1-bfc1cbc33fcd.png">

IE8 (without `es5-shim`):
<img width="520" alt="2016-02-24 16 50 26" src="https://cloud.githubusercontent.com/assets/1289884/13280061/ca4f4b62-db16-11e5-99fe-942cf1207ef8.png">

Chrome:
<img width="437" alt="2016-02-24 16 31 37" src="https://cloud.githubusercontent.com/assets/1289884/13279651/4dc351c6-db14-11e5-9e71-d00d41cf1c10.png">

**Comment by ljharb** [comment]
Does this happen with just `new Date()` as well?

**Comment by riophae** [comment]
@ljharb No, just `new Date()` is fine.

**Comment by ljharb** [comment]
hm, interesting, thanks! I'll fix this ASAP.

Curious tho, how did you discover this? Passing a date object into `new Date` is super odd.

**Comment by riophae** [comment]
Haha, we were to copy a `Date` object by passing it into `new Date` :D

**Comment by ljharb** [comment]
not `new Date(+date)`? :-)
