### ISSUE TITLE
Shim for Function::bind throws error for non-minified React 

### ISSUE THREAD

**Issue by mendelk** [es-shims/es5-shim#390]
I apologize if this is reported elsewhere, or if it's the intended behavior, or not es5-shim's fault (which it probably isn't), but I can't be the only one dealing with this!

The problem is that [this](https://output.jsbin.com/baxoqofize/4) throws an error in IE8:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.5/es5-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.5/es5-sham.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react.js"></script>
<script>
  var Hello = React.createClass({
    displayName: "Hello",
    render: function() {
      return "<p>Hello</p>";
    }
  });
</script>
```

As far as I can tell, this is because of [this](https://github.com/facebook/react/blob/ef2b1f26efb61ab18eac6919c3e55c46bfa3d385/src/isomorphic/classic/class/ReactClass.js#L799-L801) code:

```js
injectedMixins.forEach(
  mixSpecIntoComponent.bind(null, Constructor)
);
```

Now, es5-shim uses [isCallable](https://npmjs.com/is-callable) to determine if something can be `bind`ed. 

For some reason, `mixSpecIntoComponent` fails the `isCallable` test, in particular because it passes the `isES6ClassFn(value)` test, thus `throw`ing [this](https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L199-L201) error.

What gives?

Strangely, [the problem does not occur](https://output.jsbin.com/baxoqofize/3) when using the minified version.

*Note FWIW: I'm testing this on IE8 on Win7 via VirtualBox VM from a MBP*

Thank you so much for this awesome lib!

**Comment by ljharb** [comment]
`isES6ClassFn` should only be able to pass when something is a native "class" - which shouldn't be possible in IE 8.

Thank you for the jsbin - I'll take a look at this this weekend and see if I can figure it out. What's likely happening is that the non-minified version is triggering the regex in `isCallable` but the minified version is not.

**Comment by mendelk** [comment]
Thanks. Let me know if there's anything I can do to help.

**Comment by wski** [comment]
Just leaving a note here to follow this issue, having the same issue in our project (We think from f2236f6c719ee07e0a4d520567516698aba657eb) getting `TypeError: Function.prototype.bind called on incompatible function mixSpecIntoComponent(Constructor, spec)` Will report back here if we find anything that can help solve this issue.

**Comment by kurttheviking** [comment]
I've confirmed this on actual WinXP/IE8 as well for unminified versions (yes, we support this)

**Comment by ljharb** [comment]
Thanks everybody! I promise I'll have a fix out this weekend.

**Comment by wski** [comment]
You da man @ljharb!

**Comment by ljharb** [comment]
Figured out the issue in `is-callable`. It's a stupid mistake in a regex. Will have a release of both out shortly.

**Comment by ljharb** [comment]
Released as v4.5.7

**Comment by mendelk** [comment]
Confirming that issue has been fixed. Thanks @ljharb!

**Comment by kurttheviking** [comment]
thanks @ljharb -- confirmed on ye olde xp machine
