### ISSUE TITLE
Can't find version 4.0.3 in npm repository

### ISSUE THREAD

**Issue by efren-oneill** [es-shims/es5-shim#391]
I'm trying to install Canvas LMS in Ubuntu and the installation requires version 4.0.3 of es5-shim.

Installation is trying to download the file from https://registry.npmjs.org/es5-shim/-/es5-shim-4.0.3.tgz, but the file doesn't seem to be available.

**Comment by ljharb** [comment]
You want to be using the latest version anyways, which is v4.5.7 - I'm not sure why 4.0.3 isn't published, and I will publish it now, but please report to Canvas LMS that they should be requiring `^` ranges, so they get all nonbreaking changes automatically.

**Comment by ljharb** [comment]
Hmm, it looks like v4.0.3 never successfully published to npm, and I can't publish over it. I'm not sure why Canvas LMS is depending on it at all.

**Comment by efren-oneill** [comment]
Thank you for the pointer. Found the file that depends on es5-shim and updated with the latest version. Installed Canvas LMS without any error after that.

**Comment by grahamb** [comment]
canvas-lms has a dependency on grunt-contrib-jasmine, which has es5-shim as a dependency. canvas-lms has been shrinkwrapped, so that's pinned the es5-shim dep at 4.0.3.

See instructure/canvas-lms#791

**Comment by ljharb** [comment]
I followed up with npm on this, and they can't find any evidence of `v4.0.2` or `v4.0.3` ever being in npm, nor do they retain logs from that long ago. :-/

However, this is a great reason why shrinkwrap should never be used except on a top-level app. Sorry for the inconvenience!
