### ISSUE TITLE
set shims?

### ISSUE THREAD

**Issue by mockdeep** [es-shims/es5-shim#407]
Lodash uses [`Set.prototype.forEach()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach), which wasn't introduced until relatively recently in some browsers. Any chance of getting a polyfill for this in `es5-shim`?

**Comment by hazzik** [comment]
Shouldn't it be in es6 shim already?

**Comment by ljharb** [comment]
Sets are in ES6, not ES5. Use https://github.com/paulmillr/es6-shim and you'll get `Set`.

**Comment by mockdeep** [comment]
Ah, yeah, just came across that. Thanks!
