### ISSUE TITLE
[IE8] Array.prototype.slice.call(NodeList) fails

### ISSUE THREAD

**Issue by WebReflection** [es-shims/es5-shim#408]
Literally what the subject says:

``` js
Array.prototype.slice.call(document.querySelectorAll('*'));
```

This code fails in IE8.
The debugger points at these lines:
https://github.com/es-shims/es5-shim/blob/922bfc2a3f930f2441d4aaaa60954d8d00dc9070/es5-shim.js#L271-L276

live test page that fails in IE8:
http://webreflection.github.io/document-register-element/test/examples/ie8.html

**Comment by ljharb** [comment]
I believe this is caused by #99.

**Comment by Xotic750** [comment]
On [MSDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Streamlining_cross-browser_behavior) they fix this by testing
```
  try {
    // Can't be used with DOM elements in IE < 9
    _slice.call(document.documentElement);
  } catch (e) { // Fails in IE < 9
```
and then use a hand written slice instead of native call. I don't think it's the `apply` with non-array issue?

**Comment by WebReflection** [comment]
any update on this?

**Comment by WebReflection** [comment]
TBH, I just went maintenance mode today and went through all [issues](https://github.com/issues) I've opened/left behind: this was one of them.

I believe the PR would be something like:
```js
try {
  array_slice.call(document.documentElement.childNodes);
} catch(o_O) {
  array_slice = function () {
    for (var r = [], i = this.length; i--; r[i] = this[i]);
    return r.slice.apply(r, arguments);
  };
}
```
'cause I couldn't care less about IE8 performance ... but I also have no time for an official PR and tests here, sorry about that

**Comment by WebReflection** [comment]
no interest in this

**Comment by ljharb** [comment]
I still have interest in it.

**Comment by WebReflection** [comment]
OK, I am not going to do anything about it, hence I'd like to remove this ticket from my list of Github issues

**Comment by WebReflection** [comment]
do you mind opening another issue so this disappears from my list of issues? thanks
