### ISSUE TITLE
callback function of Array.prototype.forEach for isCallable return false because of class type "[object Array Iterator]" 

### ISSUE THREAD

**Issue by hero78119** [es-shims/es5-shim#414]
Sample code
```
var anArray = ["a", "b", "c"];
anArray.forEach(function (aChar) {
    console.log(aChar);
})
```

lead to exception occurring
>> Array.prototype.forEach callback must be a function

thrown in [here](https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L436)
The root cause is isCallable return false for callback function type "[object Array Iterator]". https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L70

Can reproduce on win7-IE8
Any idea?

**Comment by ljharb** [comment]
Thanks for the report! Can you provide a jsfiddle that reproduces it, and i'll take a look? `[object Array Iterator]` shouldn't exist in IE 8, so that's very confusing.

**Comment by hero78119** [comment]
In fact I find the error since

**Comment by hero78119** [comment]
Hi!
Actually I found the problem on win10 - IE11, therefore thinking it might be critical issue.
Currently I'm not on my desk of win10 PC, so only can reproduce on VM win7 + IE11(in IE8 simulation mode).  
Strange thing is win7- IE11 can not reproduce, guessing that win7 can not install the latest version of IE11 which pre-install on win10.
I will prepare more thorough result when verify again on win10+IE11 later on! 
Thanks:)

**Comment by ljharb** [comment]
@hero78119 if you can provide a jsfiddle, I can try to repro it myself on a number of Windows/IE combinations.

**Comment by hero78119** [comment]
Hi @ljharb, can not reproduce on jsfiddle.
Finally I find on my site win10-IE11 fallback to IE7 mode by default.
It might cause by missing meta
```
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```
on the site header.
(also refer to [SO](http://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do))

Close this issue first cause not relevant to es5-shim.
Thanks for your help!
