### ISSUE TITLE
es5-shim.map file missing from nuget package

### ISSUE THREAD

**Issue by WyrmUK** [es-shims/es5-shim#415]
The nuget package contains the es5-shim.js and es5-shim.min.js files, but as the es5-shim.min.js refers to es5-shim.map as a sourceMappingURL using the minified file can result in 404 errors due to the missing es5-shim.map file.
Please can you include the es5-shim.map file in future nuget package releases.

**Comment by ljharb** [comment]
I don't maintain nor recommend using a nuget package. Only ever install JS from npm.
