### ISSUE TITLE
"window.scrollTo.bind(window, 0); " runs into error(IE8) though I include es5-sham in the web page

### ISSUE THREAD

**Issue by SUpermin6u** [es-shims/es5-shim#419]
`window.scrollTo.bind(window, 0); `  works well in modern browsers when i pass it as a callback param to a function, but runs into error in IE8.
i use bind method cause i want to initialize the first param of window.scrollTop, but since it failed in IE8, so i use
`function(x){
       window.scrollTo(0, x)
 }` instead.
i also try `functin a(){}; a.bind(window)`, and it works. 
so is it a bug that  bind method of es5-sham can't deal with function on window object?

**Comment by ljharb** [comment]
Many native functions are unbindable - `console.log` can't be bound in many browsers either.

Pass `function () { window.scrollTo(0); }` instead, it's faster anyways :-)

**Comment by SUpermin6u** [comment]
ok, i get it, so dealing with native things should be careful, thanks for the quick answer
