### ISSUE TITLE
latest npm breaks tests on node between >= 1 && <= 3.3

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#442]
npm 5.2.2 breaks on node (iojs) versions 1 through 3.3

Perhaps?

`- 'if [ "${TRAVIS_NODE_VERSION%${TRAVIS_NODE_VERSION#[0-9]}}" \< "4" ]; then npm install -g npm@4.5 ; elif [ "${TRAVIS_NODE_VERSION}" != "0.6" ] && [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then npm install -g npm; fi'`

**Comment by ljharb** [comment]
Fixed in 7f6ddd6294da87d57311da585bbf776e37bc5c60
