### ISSUE TITLE
JQuery ajax in ie8 with es5-shim throw TypeError

### ISSUE THREAD

**Issue by Justinidlerz** [es-shims/es5-shim#443]
Function.prototype.bind throw a TypeError  
`[Object DispHTMLWindow2]` is not in `isCallable` function judgment types
![image](https://user-images.githubusercontent.com/7475347/27114606-714d11ea-50f7-11e7-9e17-7ade1811cca5.png)

**Comment by Justinidlerz** [comment]
And the DispHTMLWindow2 function call type is `[object Object]`

**Comment by ljharb** [comment]
I'm confused, what's "DispHTMLWindow2"? `window` should report `[object Window]`.

Is this normal IE 8, or is it in compatibility mode?

Also, can you show me the code that triggers this?

**Comment by Justinidlerz** [comment]
I'm so sorry for new this issues.
The bug is not cause from `es5-shim`
But the same code can run >= ie9, (PS: not add `es5-shim`).
The bug cause from like this code:
```javascript
var $ = require('jquery');
var getData = function(url, data, callback) {
  return $.ajax({
       url: url,
       dataType: 'jsonp',
       data: data,
       success: function(){  //... }
   })
}
getData('//test.domain.com/jsonp', {  a: 1 }, function (){ 

});
// throw error, because the data i parse a function
getData('//test.domain.com/jsonp', function(){

});

```
