### ISSUE TITLE
Rounding errors with toExponential in Edge 15/16

### ISSUE THREAD

**Issue by Niggler** [es-shims/es5-shim#453]
See https://github.com/Microsoft/ChakraCore/issues/3929 and https://github.com/Microsoft/ChakraCore/issues/4421 .  Reproducible example:

```js
(-6.9e-11).toExponential(4);
```

Pretty much every other JS engine, even IE8+, give the expected `"-6.9000e-11"` but Edge 15/16 give `"-6.8000e-11"`

ping @ljharb

**Comment by obastemur** [comment]
The issue was fixed on ChakraCore release1.8. The same fix should apply to upcoming Edge release.

**Comment by ljharb** [comment]
@obastemur do you know which edge version ended up fixing it?

**Comment by obastemur** [comment]
@ljharb Edge17 should be fine. (just tested and it works)

**Comment by SheetJSDev** [comment]
FYI this is still a failure in Edge17 revision 17.17134 (the version used in sauce labs)
