### ISSUE TITLE
IE9 error: Redeclaration of const property

### ISSUE THREAD

**Issue by lapo-luchini** [es-shims/es5-shim#454]
A website of mine that uses es5-shim doesn't load on IE9, it gives this error:
![image](https://user-images.githubusercontent.com/420454/35674725-eb77ad22-0745-11e8-8ef5-80c6f92881a0.png)
I guess the line of the error is wrong, as that line is just a function declaration and doesn't assign any property… but no stack trace is given at all.

**Comment by JakeChampion** [comment]
How are you including the shim? I don't think it uses `const` anywhere in the codebase.

**Comment by lapo-luchini** [comment]
Usually I'm using UglifyJS 3.x to minimize all "third-part scripts" together, but since I didn't understand the error line, I tried using the scripts simply concatenated one after the other (with no minification applied) and that's the result I reported in the screenshot. es5-shim is the first file included in the concatenation (then follows es6-shim and jquery and other stuff) and it stops on the first line, so I guess all the rest of the content doesn't really matter much.

**Comment by lapo-luchini** [comment]
I created a [minimal test-case](https://jsbin.com/wutititoye)… and it does load correctly.
OK, sorry, I'm puzzled, I'll have to dig in deeper.

**Comment by lapo-luchini** [comment]
If anyone is curious, the "real" problem is that IE9 reports the error on the first line of code (but comments don't count!) wherever it happens.
