### ISSUE TITLE
Something in the shim causes Chrome to throw a warning

### ISSUE THREAD

**Issue by NoahAndrews** [es-shims/es5-shim#456]
See https://github.com/ljharb/object-keys/issues/46, which was solved by @ljharb, the primary committer here

**Comment by ljharb** [comment]
Specifically, https://github.com/ljharb/object-keys/commit/f09421a6fca35c89a0b8bbfad1fb67cef98f5ac7.

**Comment by NoahAndrews** [comment]
Thanks! Is there a release imminent?

**Comment by ljharb** [comment]
Once i resolve some test failures.
