### ISSUE TITLE
Question: Why concatenate Symbols with a string without assigning it to a variable?

### ISSUE THREAD

**Issue by lukastaegert** [es-shims/es5-shim#462]
When making sure that Rollup is able to handle this shim without unexpected tree-shaking, I became upon this line, which is removed by Rollup:

https://github.com/es-shims/es5-shim/blob/d5297adf9a9ca5669b3d43153fa2d8092e879f9c/es5-shim.js#L2027

Is this line actually correct or should it rather be something like `str = '' + str`?

Otherwise I fail to see what the side-effect should be. If it is a thrown error, I am missing the try-statement. Please tell me if I overlook anything here.

**Comment by ljharb** [comment]
It's correct, because implicit String coercion causes Symbols to throw, and this line is intended to replicate that exception. Removing this line will cause code that shouldn't work, to start working.

**Comment by lukastaegert** [comment]
Thanks for explaining. Not sure if we are going to fix this one soon, everything else here is working fine, though. A simple way to prevent tree-shaking could be to put this in a place where the return value is used, e.g.

```js
function parseInt(str, radix) {
  var string = trim(String(typeof str === 'symbol' ? '' + str : str));
  var defaultedRadix = $Number(radix) || (hexRegex.test(string) ? 16 : 10);
  return origParseInt(string, defaultedRadix);
};
```

I do not suppose this is something you would consider? Tackling this via static analysis from our side will be quite hard, and deoptimizing all string concatenations is a really high price for a runtime error that should not occur in proper code.

**Comment by ljharb** [comment]
How often does a noop string concat occur in code such that you need to ever remove it anywhere? Is that really. common pattern?

**Comment by lukastaegert** [comment]
Probably as often as this runtime error—usually due to an error on the developer's side 😜
But yes, we could check for this specific pattern.

**Comment by ljharb** [comment]
I think it's safe to leave that to a linter catching noop statements :-)

**Comment by lukastaegert** [comment]
You would be surprised as to how many people do not lint...

Still, catching it now on our side with a specific heuristic: rollup/rollup#2917
