### ISSUE TITLE
in ie8 Object.keys failed this conversion

### ISSUE THREAD

**Issue by zongzheng123** [es-shims/es5-shim#464]
it's my webpack4 configuration => `entry: ['es5-shim/es5-sham', 'es5-shim', 'babel-polyfill',  './src/index.js'],`
it's error message => `SCRIPT438: Object does not support "keys" properties or methods`
give me a hand plesase, thanks

**Comment by ljharb** [comment]
You have to load the es5-shim *before* the es5-sham; what happens if you do that?

**Comment by zongzheng123** [comment]
> You have to load the es5-shim _before_ the es5-sham; what happens if you do that?

thanks for you and i find the reason.i work  with webpack 4 devServer, a file named common.js generated by default and it's at the top of all the files

**Comment by zongzheng123** [comment]
> You have to load the es5-shim _before_ the es5-sham; what happens if you do that?

thanks for you,This may not be problem of es5-shim

**Comment by ljharb** [comment]
Closing then; happy to reopen if it's still an issue.
