### ISSUE TITLE
External URL linking to spam websites

### ISSUE THREAD

**Issue by animamundi** [es-shims/es5-shim#478]
The URL linked here https://github.com/es-shims/es5-shim/blob/v2.0.5/es5-shim.js#L545 is referencing spam websites. `whattheheadsaid.com` seems to have been sold or hijacked or something, I don't know but it doesn't seem safe to keep in the source code.

**Comment by CircleTan** [comment]
你的邮件我已收到了，谢谢。

**Comment by ljharb** [comment]
Thanks - i'll replace it with https://web.archive.org/web/20140727042234/http://whattheheadsaid.com/2010/10/a-safer-object-keys-compatibility-implementation
