### ISSUE TITLE
Invalid Date on Safari

### ISSUE THREAD

**Issue by Semigradsky** [es-shims/es5-shim#481]
```
> new Date('1900-01-01T00:00:00.000')
< Invalid Date
```
es5-shim@4.6.5
Safari 15.3

**Comment by CircleTan** [comment]
你的邮件我已收到了，谢谢。

**Comment by ljharb** [comment]
This date works fine without the shim, and I do see that it's invalid with it.

Date parsing is wildly underspecified; that said, this date parses natively in Safari and Chrome and Firefox, so the es5-shim shouldn't be breaking it.
