### ISSUE TITLE
⚠️ `webkitStorageInfo` is going away

### ISSUE THREAD

**Issue by tomayac** [es-shims/es5-shim#482]
I don't think it's a major issue for this package, but just wanted to let you know that on the Chrome team we're planning on removing `webkitStorageInfo`, which you use: https://github.com/es-shims/es5-shim/blob/bcdbd318b48c39c3cd822b1a36bcaa4538cf573c/es5-shim.js#L1074

Just a heads up. Already today the naming of the interface you get back has changed:

```js
window.webkitStorageInfo
// DeprecatedStorageInfo {}
```

**Comment by ljharb** [comment]
The only way we use it is to exclude it, since it does the very terrible thing (that i hope no new globals ever do) of logging to the console merely by accessing the global, so we shouldn’t be impacted. Thanks for the heads up!
